import { NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req) {
  try {
    const body = await req.json();

    const { name, email, company, phone, message, budget } = body;

    if (!name || !email || !message) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const { data, error } = await resend.emails.send({
      from: 'Contact Form <notreply@resend.dev>',
      to: process.env.CONTACT_FORM_RECEIVER || 'jsoto7087@gmail.com',
      subject: 'New Contact Submission',
      html: `
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <title>Contact Submission</title>
          </head>
          <body style="font-family: Arial, sans-serif; background-color: #f9fafb; margin: 0; padding: 0;">
            <table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 24px;">
              <tr>
                <td align="center" style="padding-bottom: 20px;">
                  <img src="https://sotodev.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FfullLogo.0d782fd6.png&w=3840&q=75" alt="SotoDev Logo" width="240" height="auto" style="display: block; margin: 0 auto;" />
                </td>
              </tr>
              <tr>
                <td>
                  <h2 style="text-align: center; color: #1e3a8a;">New Contact Submission</h2>
                  <p style="color: #334155; font-size: 14px;">You’ve received a new message from your contact form. Below are the details:</p>
                  <table cellpadding="4" cellspacing="0" width="100%" style="margin-top: 16px;">
                    <tr><td><strong>Name:</strong></td><td>${name}</td></tr>
                    <tr><td><strong>Email:</strong></td><td>${email}</td></tr>
                    <tr><td><strong>Company:</strong></td><td>${company || 'N/A'}</td></tr>
                    <tr><td><strong>Phone:</strong></td><td>${phone || 'N/A'}</td></tr>
                    <tr><td><strong>Budget:</strong></td><td>${budget || 'N/A'}</td></tr>
                    <tr><td colspan="2" style="padding-top: 12px;"><strong>Message:</strong><br />${message}</td></tr>
                  </table>
                  <p style="color: #6b7280; font-size: 12px; text-align: center; margin-top: 32px;">This email was generated by the SotoDev web application. Visit us at <a href="https://sotodev.com" style="color: #1e3a8a; text-decoration: none;">sotodev.com</a>.</p>
                </td>
              </tr>
            </table>
          </body>
        </html>
      `,
    });

    if (error) {
      console.error('Email send error:', error);
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 });
    }

    return NextResponse.json({ success: true, data });
  } catch (err) {
    console.error('Unexpected error:', err);
    return NextResponse.json({ error: 'Unexpected error' }, { status: 500 });
  }
}